# test-00_compute_error.R
#
# Purpose:
#   This script tests the fundamental features of 00_compute_error.R,
#   checking that the resulting .rds file generated by the script has these
#   characteristics:
#       - is a data.frame with the expected column names
#       - has the expected number of rows
#       - was generated in the right folder
#       - covers every combination of dimension and magnification exactly once
#       - has error metrics (ERR_L1, ERR_CLR) that are non-negative and a
#         Pielou index bounded between 0 and 1
#       - contains no NA values
#
# Inputs:
#   - compositional_effects_01.rds
#
# Outputs:
#   - test results printed to the console (pass/fail for each check)
#
# Note:
#   This script does not source 00_compute_error.R directly, since doing
#   so would re-run the full parallelized simulation (8 toy_model() calls,
#   N = 10,000 samples each) on every test run. Instead, it validates the
#   already-saved output (compositional_effects_01.rds) directly. Trade-off:
#   these tests check that the saved output is well-formed and internally
#   consistent, but will NOT catch a logic change in 00_compute_error.R
#   unless the .rds file is regenerated afterwards.

# testthat: allows to write tests for the other scripts
# https://cran.r-project.org/web/packages/testthat/index.html
library(testthat)
# here: builds file paths relative to the project root
# https://cran.r-project.org/web/packages/here/index.html
library(here)
# vegan: tools for descriptive community ecology (diversity indices, ordination)
# https://cran.r-project.org/web/packages/vegan/index.html
library(vegan)


# -------- load the simulation results to test --------

# search recursively for the target .rds file and load it directly
results <- readRDS(list.files(
  path = here(),
  pattern = "^compositional_effects_01\\.rds$",
  full.names = TRUE,
  recursive = TRUE
))


# -------- test output structure --------

test_that("results is a data frame with the expected columns", {
  # confirm the object inherits the data.frame class
  expect_s3_class(results, "data.frame")
  # confirm column names match the expected output schema exactly
  expect_named(results, c("d", "m", "ERR_L1", "ERR_CLR", "Pielou"))
})

test_that("results has the expected number of rows", {
  # dimensions has 4 values: seq(5, 200, by = 50) = 5, 55, 105, 155
  # (205 would exceed the upper bound of 200, so it's excluded)
  # magnification has 2 values -> 4 * 2 = 8 rows
  expected_rows <- length(seq(5, 200, by = 50)) * length(c(1, 2))
  expect_equal(nrow(results), expected_rows)
})


# -------- test output file --------

test_that("output .rds file exists at the expected location", {
  # search for the dataset path then keeps only the .rds file name
  exp_file_name <- basename(list.files(
    path = here(),
    pattern = "compositional_effects_01.rds",
    full.names = TRUE,
    recursive = TRUE
  ))
  file_name <- "compositional_effects_01.rds"
  expect_equal(exp_file_name, file_name)
})


# -------- test parameter coverage --------

test_that("all dimension values are present in results", {
  # every value in seq(5, 200, by = 50) must appear at least once
  expect_setequal(unique(results$d), seq(5, 200, by = 50))
})

test_that("all magnification values are present in results", {
  # both magnification levels must be represented in the output
  expect_setequal(unique(results$m), c(1, 2))
})

test_that("each (d, m) combination appears only once", {
  # duplicated rows would indicate a parallelization merge error
  duos <- paste(results$d, results$m)
  expect_false(any(duplicated(duos)))
})


# -------- test metric validity --------

test_that("ERR_L1 and ERR_CLR are non-negative", {
  # errors are absolute values, so they must never be negative
  expect_true(all(results$ERR_L1 >= 0))
  expect_true(all(results$ERR_CLR >= 0))
})

test_that("Pielou evenness is bounded between 0 and 1", {
  # Pielou index is a normalised entropy, strictly in [0, 1]
  expect_true(all(results$Pielou >= 0))
  expect_true(all(results$Pielou <= 1))
})

test_that("results contain no NA values", {
  # any NA signals a failed simulation run
  expect_false(anyNA(results))
})
