# test-norta_example_script.R
#
# Purpose:
#   this script tests the main features of the norta_example_script.R script,
#   checking:
#       - the R matrix is symmetric and contains the expected values
#       - the NorTA matrix has the expected dimensions and structure
#       - the inverse CDF transformation returns non-negative integer values
#
# Inputs:
#   - norta_example_script.R script (sourced below)
#   - matrixes and parameters generated by the sourced script
#
# Outputs:
#   - test results printed to the console (pass/fail for each check)

# here: builds file paths relative to the project root
# https://cran.r-project.org/web/packages/here/index.html
library(here)
# testthat: allows to write tests for the other scripts
# https://cran.r-project.org/web/packages/testthat/index.html
library(testthat)
# Collection of packages for data wrangling and visualization
# https://cran.r-project.org/web/packages/tidyverse/index.html
library(tidyverse)


# -------- load script to test --------
source(
  list.files(
    path = here(),
    pattern = "^norta_example_script\\.R$",
    full.names = TRUE,
    recursive = TRUE
  )
)


# -------- test for the R matrix --------

# test that R matrix is symmetric
test_that("R is a symmetric matrix", {
  expect_true(isSymmetric.matrix(R))
})

# test that the matrix entry [2, 4] has the proper value
test_that("Matrix entry [2, 4] is exactly -0.9", {
  expect_true(R[2, 4] == -0.9)
})

# testing that [4, 2] entry is equal to [2, 4] entry
test_that("Matrix entries in positions [4, 2] and [2, 4] are identical", {
  expect_equal(R[4, 2], R[2, 4])
})


# -------- test the applying of the inverse CDF function --------

# testing that NorTa is a matrix
test_that("NorTa is a matrix", {
  expect_true(is.matrix(NorTA))
})

test_that("NorTA dimensions are: - rows = n = 10^3; - columns = D = 5;", {
  expect_equal(nrow(NorTA), n)
  expect_equal(ncol(NorTA), D)
})

test_that("NorTA have values greater than or equal to zero", {
  expect_true(all(NorTA >= 0))
  expect_true(all(NorTA == floor(NorTA)))
})
